/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Morena.MorenaStudio;
import DAO.UsuarioDAO;
import DAO.funcionarioDAO;
import Logica.Funcionario;
import Logica.Usuario;
import ModelTable.FuncionarioTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import util.Util;
import java.util.logging.Level;
import java.util.logging.Logger;
import Relatorios.chamar;
import java.io.File;
import java.sql.SQLException;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Guilherme
 */
public class JIFGerencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFGerencia
     */
    public JIFGerencia() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_matri = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tf_matri = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfRG = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfend = new javax.swing.JTextField();
        tfSexo = new javax.swing.JComboBox();
        tfEstado = new javax.swing.JComboBox();
        tfId = new javax.swing.JTextField();
        lbl_adm = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFCPF = new javax.swing.JFormattedTextField();
        jFnascimento = new javax.swing.JFormattedTextField();
        jFAdm = new javax.swing.JFormattedTextField();
        jFexo = new javax.swing.JFormattedTextField();
        jFContato = new javax.swing.JFormattedTextField();
        jCBSec = new javax.swing.JComboBox();
        tf_Funcao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfPesquisarNome = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        lbl_mat = new javax.swing.JLabel();
        txt_mat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlterar = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btVOltar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btdecla = new javax.swing.JButton();
        scan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfprate = new javax.swing.JTextField();
        lbl_mat1 = new javax.swing.JLabel();
        tfcaixa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfenve = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Gerencia de Funcionários");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro de Funcionários "));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("RG:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Nascimento:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Sexo:");

        lbl_matri.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_matri.setText("Matricula:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Contato:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Cidade:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Estado:");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCidadeActionPerformed(evt);
            }
        });

        tfRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRGActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Endereço");

        tfSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "Masculino", "Feminino" }));
        tfSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSexoActionPerformed(evt);
            }
        });

        tfEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));
        tfEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEstadoActionPerformed(evt);
            }
        });

        lbl_adm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_adm.setText("Admissão:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Exoneração:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Secretaria:");

        try {
            jFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFCPFActionPerformed(evt);
            }
        });

        try {
            jFnascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFnascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnascimentoActionPerformed(evt);
            }
        });

        try {
            jFAdm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFAdmActionPerformed(evt);
            }
        });

        try {
            jFexo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jCBSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "Administração", "Agricultura", "Assistência Social", "Cultura", "Educação", "Finanças", "Meio Ambiente", "Obras", "Relações Institucionais", "Saúde", "Trabalho" }));

        tf_Funcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FuncaoActionPerformed(evt);
            }
        });

        jLabel13.setText("Função:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_adm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_matri, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCBSec, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_Funcao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFexo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFContato, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_matri))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfend, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(tfend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_adm)
                    .addComponent(jLabel7)
                    .addComponent(jFAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Funcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matri)
                    .addComponent(tf_matri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jCBSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jFContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisar Funcionários"));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nome:");

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Zoom.png"))); // NOI18N
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        lbl_mat.setText("Matricula:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lbl_mat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mat)
                    .addComponent(txt_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbAlterar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlterarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAlterar);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btSalvar.setBackground(new java.awt.Color(0, 0, 255));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(204, 0, 0));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Remove.png"))); // NOI18N
        btExcluir.setToolTipText("Deletar");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btVOltar.setBackground(new java.awt.Color(0, 204, 0));
        btVOltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Previous.png"))); // NOI18N
        btVOltar.setToolTipText("Voltar");
        btVOltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVOltarActionPerformed(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(0, 0, 204));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Refresh.png"))); // NOI18N
        btAlterar.setToolTipText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btdecla.setBackground(new java.awt.Color(0, 0, 255));
        btdecla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Text.png"))); // NOI18N
        btdecla.setToolTipText("Gerar Declaração");
        btdecla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeclaActionPerformed(evt);
            }
        });

        scan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Copy.png"))); // NOI18N
        scan.setToolTipText("Escanear documento");
        scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(scan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btdecla, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVOltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btdecla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVOltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scan.getAccessibleContext().setAccessibleDescription("Escanear documento");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Localização Física"));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Prateleira:");

        tfprate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprateActionPerformed(evt);
            }
        });

        lbl_mat1.setText("Caixa:");

        jLabel15.setText("Envelope:");

        tfenve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfenveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfprate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_mat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfcaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfenve, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfprate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mat1)
                    .addComponent(tfcaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfenve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(921, 921, 921)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCidadeActionPerformed

    private void tfEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEstadoActionPerformed

    private void tbAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlterarMouseClicked
        // TODO add your handling code here:
        tfId.setEnabled(false);
        btExcluir.setEnabled(true);
        btPesquisar.setEnabled(false);
        btAlterar.setEnabled(true);

        if (evt.getClickCount() == 2) {
            Object obj = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 0));
            Object obj2 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 1));
            Object obj3 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 2));
            Object obj4 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 3));
            Object obj5 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 4));
            Object obj6 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 5));
            Object obj7 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 6));
            Object obj8 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 7));
            Object obj9 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 8));
            Object obj10 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 9));
            Object obj11 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 10));
            Object obj12 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 11));
            Object obj13 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 12));
            Object obj14 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 13));
            Object obj15 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 14));
            Object obj16 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 15));
            Object obj17 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 16));
            Object obj18 = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 17));

            String Id = obj.toString();
            String Nome = obj2.toString();
            String Telefone = obj3.toString();
            String Endereco = obj4.toString();
            String Cidade = obj5.toString();
            String Estado = obj6.toString();
            String DataNascimento = obj7.toString();
            String Sexo = obj8.toString();
            String CPF = obj9.toString();
            String RG = obj10.toString();
            String Admissao = obj11.toString();
            String Funcao = obj12.toString();
            String Matricula = obj13.toString();
            String Exoneracao = obj14.toString();
            String Secretaria = obj15.toString();
            String Prateleira = obj16.toString();
            String Caixa = obj17.toString();
            String Envelope = obj18.toString();

            tfId.setText(Id);//aqui pego o valor da linha selecionada na coluna 0 e adiciono ao jtextfield
            tfNome.setText(Nome);
            jFCPF.setText(CPF);
            tfCidade.setText(Cidade);
            tf_matri.setText(Matricula);
            jFnascimento.setText(DataNascimento);
            tfRG.setText(RG);
            tfend.setText(Endereco);
            jFContato.setText(Telefone);
            jCBSec.setSelectedItem(Secretaria);
            jFexo.setText(Exoneracao);
            jFAdm.setText(Admissao);
            tfEstado.setSelectedItem(Estado);
            tfSexo.setSelectedItem(Sexo);
            tf_Funcao.setText(Funcao);
            tfprate.setText(Prateleira);
            tfcaixa.setText(Caixa);
            tfenve.setText(Envelope);

        }

    }//GEN-LAST:event_tbAlterarMouseClicked

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        Util u = new Util();
        Util.CPF(jFCPF.getText());
        String valor;
        valor = (String) tfSexo.getSelectedItem();
        String valor2 = (String) tfEstado.getSelectedItem();
        String valor3 = (String) jCBSec.getSelectedItem();
        if (Util.chkVazio(tfNome.getText(), tfCidade.getText(), tf_matri.getText(),
                jFnascimento.getText(),
                jFCPF.getText(), tfRG.getText(), jFContato.getText(), jFAdm.getText(), tf_Funcao.getText(), jFexo.getText(), tfprate.getText(), tfcaixa.
                getText(), tfenve.getText())) {

            if (Util.CPF(jFCPF.getText())) {
                if (u.dataValida(jFnascimento.getText())) {
                    if (u.dataValida(jFAdm.getText())) {
                        if (u.dataValida(jFexo.getText())) {

                            Funcionario fun = new Funcionario();
                            fun.setNome(tfNome.getText());
                            fun.setCpf(jFCPF.getText());
                            fun.setCidade(tfCidade.getText());
                            fun.setMatricula(tf_matri.getText());
                            fun.setEstado(valor2);
                            fun.setNascimento(jFnascimento.getText());
                            fun.setRg(tfRG.getText());
                            fun.setEndereco(tfend.getText());
                            fun.setSexo(valor);
                            fun.setTelefone(jFContato.getText());
                            fun.setSecretaria(valor3);
                            fun.setAdmissao(jFAdm.getText());
                            fun.setExoneracao(jFexo.getText());
                            fun.setFuncao(tf_Funcao.getText());
                            fun.setPrateleira(tfprate.getText());
                            fun.setCaixa(tfcaixa.getText());
                            fun.setEnvelope(tfenve.getText());

                            funcionarioDAO dao = new funcionarioDAO();
                            dao.salvar(fun);
                            limpaCampos();

                            JOptionPane.showMessageDialog(rootPane, "Cadastro de Funcionário realizado com Sucesso!");
                            List<Funcionario> funcionarios = dao.pesquisaNomeiLike("");
                            FuncionarioTableModel ftm = new FuncionarioTableModel(funcionarios);
                            tbAlterar.setModel(ftm);
                        }
                    }
                }
            }


    }//GEN-LAST:event_btSalvarActionPerformed
    }


    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        Util u = new Util();
        funcionarioDAO fDAO = new funcionarioDAO();
        Funcionario fun = new Funcionario();
        Object obj = (tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 0));
        String Id = obj.toString();
        fun = fDAO.pesquisaID(Integer.parseInt(Id));
        int i = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse Funcionário?", "Messagem", JOptionPane.WARNING_MESSAGE);
        if (i == JOptionPane.YES_OPTION) {
            fDAO.remover(fun);
            List<Funcionario> funcionarios = fDAO.pesquisaNomeiLike("");
            FuncionarioTableModel ftm = new FuncionarioTableModel(funcionarios);
            tbAlterar.setModel(ftm);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não Excluído!");
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    private void btVOltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVOltarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btVOltarActionPerformed

    private void tfSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSexoActionPerformed

    private void tfRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRGActionPerformed

    private void jFCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFCPFActionPerformed

    private void jFnascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFnascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFnascimentoActionPerformed

    private void jFAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFAdmActionPerformed

    private void tf_FuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FuncaoActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:

        funcionarioDAO fDAO = new funcionarioDAO();
        //Texto digitado para pesquisa
        List<Funcionario> func = new ArrayList<>();
        List<Funcionario> funcionarios = fDAO.pesquisaNomeiLike(tfPesquisarNome.getText());
        if (Util.chkSize(funcionarios, tfPesquisarNome.getText())) {
            FuncionarioTableModel ftm = new FuncionarioTableModel(funcionarios);
            tbAlterar.setModel(ftm);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void tfenveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfenveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfenveActionPerformed

    private void tfprateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfprateActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        btPesquisar.setEnabled(true);
        Funcionario Fun = new Funcionario();
        funcionarioDAO fDAO = new funcionarioDAO();
        String valor = (String) tfEstado.getSelectedItem();
        String valor2 = (String) tfSexo.getSelectedItem();
        String valor3 = (String) jCBSec.getSelectedItem();
        Fun = fDAO.pesquisaID(Integer.parseInt(tfId.getText()));
        Util u = new Util();
        if (Util.chkVazio(tfNome.getText(), tfCidade.getText(), tf_matri.getText(),
                jFnascimento.getText(),
                jFCPF.getText(), tfRG.getText(), jFContato.getText(), tf_Funcao.getText(), jFAdm.getText(), jFexo.getText(), tfprate.getText(), tfcaixa.
                getText(), tfenve.getText())) {
            if (u.dataValida(jFnascimento.getText())) {
                if (u.dataValida(jFAdm.getText())) {
                    if (u.dataValida(jFexo.getText())) {
                        if (Util.CPF(jFCPF.getText())) {

                            Fun.setNome(tfNome.getText());
                            Fun.setCpf(jFCPF.getText());
                            Fun.setCidade(tfCidade.getText());
                            Fun.setMatricula(tf_matri.getText());
                            Fun.setEstado(valor);
                            Fun.setNascimento(jFnascimento.getText());
                            Fun.setRg(tfRG.getText());
                            Fun.setEndereco(tfend.getText());
                            Fun.setSexo(valor2);
                            Fun.setTelefone(jFContato.getText());
                            Fun.setSecretaria(valor3);
                            Fun.setAdmissao(jFAdm.getText());
                            Fun.setExoneracao(jFexo.getText());
                            Fun.setFuncao(tf_Funcao.getText());
                            Fun.setPrateleira(tfprate.getText());
                            Fun.setCaixa(tfcaixa.getText());
                            Fun.setEnvelope(tfenve.getText());

                            fDAO.Alterar(Fun);

                            JOptionPane.showMessageDialog(rootPane, "Alteração de Funcionário realizada com Sucesso!");

                            limpaCampos();
                            funcionarioDAO fdao = new funcionarioDAO();
                            List<Funcionario> funcionarios = fdao.pesquisaNomeiLike("");
                            FuncionarioTableModel ftm = new FuncionarioTableModel(funcionarios);
                            tbAlterar.setModel(ftm);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btdeclaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeclaActionPerformed

        // Pre ficar entendido
        // Clia um modelo usuário e atribui os metodos da classe Dao
        Usuario usu = new UsuarioDAO().recebeUsuario();
        // Atribui o valor ao modelo
        usu.setPegaID((int) tbAlterar.getValueAt(tbAlterar.getSelectedRow(), 0));
        // Instancia a classe Dao
        UsuarioDAO usuDao = new UsuarioDAO();
        // Usa o método alterar
        usuDao.Alterar(usu);

        //Chamar o iReport
        try {
            chamar teste = new chamar();
            JasperViewer.viewReport(teste.exibirRelatorio(0), false);

        } catch (SQLException ex) {
            Logger.getLogger(JIFGerencia.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btdeclaActionPerformed

    private void scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanActionPerformed
        MorenaStudio.main(new String[]{""});

    }//GEN-LAST:event_scanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVOltar;
    private javax.swing.JButton btdecla;
    private javax.swing.JComboBox jCBSec;
    private javax.swing.JFormattedTextField jFAdm;
    private javax.swing.JFormattedTextField jFCPF;
    private javax.swing.JFormattedTextField jFContato;
    private javax.swing.JFormattedTextField jFexo;
    private javax.swing.JFormattedTextField jFnascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_adm;
    private javax.swing.JLabel lbl_mat;
    private javax.swing.JLabel lbl_mat1;
    private javax.swing.JLabel lbl_matri;
    private javax.swing.JButton scan;
    private javax.swing.JTable tbAlterar;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JComboBox tfEstado;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPesquisarNome;
    private javax.swing.JTextField tfRG;
    private javax.swing.JComboBox tfSexo;
    private javax.swing.JTextField tf_Funcao;
    private javax.swing.JTextField tf_matri;
    private javax.swing.JTextField tfcaixa;
    private javax.swing.JTextField tfend;
    private javax.swing.JTextField tfenve;
    private javax.swing.JTextField tfprate;
    private javax.swing.JTextField txt_mat;
    // End of variables declaration//GEN-END:variables
private void limpaCampos() {
        jFCPF.setText("");
        tfCidade.setText("");
        tf_matri.setText("");
        jCBSec.setSelectedItem("-");
        jFnascimento.setText("");
        tfNome.setText("");
        tfRG.setText("");
        tfend.setText("");
        jFexo.setText("");
        jFContato.setText("");
        jFAdm.setText("");
        tfEstado.setSelectedItem("-");
        tfSexo.setSelectedItem("-");
        tf_Funcao.setText("");
        tfprate.setText("");
        tfcaixa.setText("");
        tfenve.setText("");
    }

}
